name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_GATEWAY_URL: https://story-gateway-74zr6opnjq-an.a.run.app
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
